name: Question
description: Ask a question about yt-dlp usage or behavior
labels: [question]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Carefully read and work through this check list in order to prevent the most common mistakes and misuse of yt-dlp:
      options:
        - label: I'm asking a genuine question about yt-dlp and not about a specific site or bug
          required: true
        - label: I've read the [README](https://github.com/yt-dlp/yt-dlp/blob/master/README.md) and the [FAQ](https://github.com/yt-dlp/yt-dlp/wiki/FAQ)
          required: true
        - label: I've searched the [issue tracker](https://github.com/yt-dlp/yt-dlp/issues) for similar questions including closed ones
          required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Ask your question here. Be as specific as possible.
      placeholder: I want to know how to...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Add any other context, screenshots, or examples that may help answer your question.
      placeholder: I tried running the following command...
    validations:
      required: false
